version: "3.7"
services:
    odoo:
        image: odoo:15.0
        platform: linux/amd64
        container_name: odoo15
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres10_odoo15
            - USER=odoo
            - PASSWORD=odoo
    postgresql:
        image: postgres:14
        container_name: postgres10_odoo15
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
